# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import generated
from generated.models.match_team_player import MatchTeamPlayer  # noqa: E501
from generated.rest import ApiException


class TestMatchTeamPlayer(unittest.TestCase):
    """MatchTeamPlayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMatchTeamPlayer(self):
        """Test MatchTeamPlayer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = generated.models.match_team_player.MatchTeamPlayer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
