# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import generated
from generated.models.brawler_stat_list import BrawlerStatList  # noqa: E501
from generated.rest import ApiException


class TestBrawlerStatList(unittest.TestCase):
    """BrawlerStatList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrawlerStatList(self):
        """Test BrawlerStatList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = generated.models.brawler_stat_list.BrawlerStatList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
