# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import generated
from generated.api.events_api import EventsApi  # noqa: E501
from generated.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_scheduled_events(self):
        """Test case for get_scheduled_events

        Get event rotation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
