# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import generated
from generated.models.gear_stat import GearStat  # noqa: E501
from generated.rest import ApiException


class TestGearStat(unittest.TestCase):
    """GearStat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGearStat(self):
        """Test GearStat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = generated.models.gear_stat.GearStat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
