# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import generated
from generated.models.cancel_match_response import CancelMatchResponse  # noqa: E501
from generated.rest import ApiException


class TestCancelMatchResponse(unittest.TestCase):
    """CancelMatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCancelMatchResponse(self):
        """Test CancelMatchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = generated.models.cancel_match_response.CancelMatchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
