# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import generated
from generated.models.match import Match  # noqa: E501
from generated.rest import ApiException


class TestMatch(unittest.TestCase):
    """Match unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMatch(self):
        """Test Match"""
        # FIXME: construct object with mandatory attributes with example values
        # model = generated.models.match.Match()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
