# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import generated
from generated.models.set_esports_notification_response import SetEsportsNotificationResponse  # noqa: E501
from generated.rest import ApiException


class TestSetEsportsNotificationResponse(unittest.TestCase):
    """SetEsportsNotificationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetEsportsNotificationResponse(self):
        """Test SetEsportsNotificationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = generated.models.set_esports_notification_response.SetEsportsNotificationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
