# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import generated
from generated.models.accessory import Accessory  # noqa: E501
from generated.rest import ApiException


class TestAccessory(unittest.TestCase):
    """Accessory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessory(self):
        """Test Accessory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = generated.models.accessory.Accessory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
