# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import 
from .models.player import Player  # noqa: E501
from .rest import ApiException


class TestPlayer(unittest.TestCase):
    """Player unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayer(self):
        """Test Player"""
        # FIXME: construct object with mandatory attributes with example values
        # model = .models.player.Player()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
