# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import 
from .models.banned_brawler_entry import BannedBrawlerEntry  # noqa: E501
from .rest import ApiException


class TestBannedBrawlerEntry(unittest.TestCase):
    """BannedBrawlerEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBannedBrawlerEntry(self):
        """Test BannedBrawlerEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = .models.banned_brawler_entry.BannedBrawlerEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
