# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import 
from .models.match_location import MatchLocation  # noqa: E501
from .rest import ApiException


class TestMatchLocation(unittest.TestCase):
    """MatchLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMatchLocation(self):
        """Test MatchLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = .models.match_location.MatchLocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
