# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import 
from .models.register_match_request import RegisterMatchRequest  # noqa: E501
from .rest import ApiException


class TestRegisterMatchRequest(unittest.TestCase):
    """RegisterMatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegisterMatchRequest(self):
        """Test RegisterMatchRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = .models.register_match_request.RegisterMatchRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
