# coding: utf-8

# flake8: noqa
"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.accessory import Accessory
from swagger_client.models.accessory_list import AccessoryList
from swagger_client.models.banned_brawler_entry import BannedBrawlerEntry
from swagger_client.models.banned_brawler_list import BannedBrawlerList
from swagger_client.models.battle import Battle
from swagger_client.models.battle_list import BattleList
from swagger_client.models.battle_region import BattleRegion
from swagger_client.models.battle_region_list import BattleRegionList
from swagger_client.models.battle_result import BattleResult
from swagger_client.models.brawler import Brawler
from swagger_client.models.brawler_info import BrawlerInfo
from swagger_client.models.brawler_info_list import BrawlerInfoList
from swagger_client.models.brawler_list import BrawlerList
from swagger_client.models.brawler_stat import BrawlerStat
from swagger_client.models.brawler_stat_list import BrawlerStatList
from swagger_client.models.cancel_match_response import CancelMatchResponse
from swagger_client.models.client_error import ClientError
from swagger_client.models.club import Club
from swagger_client.models.club_member import ClubMember
from swagger_client.models.club_member_list import ClubMemberList
from swagger_client.models.club_ranking import ClubRanking
from swagger_client.models.club_ranking_list import ClubRankingList
from swagger_client.models.completed_game import CompletedGame
from swagger_client.models.completed_game_list import CompletedGameList
from swagger_client.models.completed_game_team import CompletedGameTeam
from swagger_client.models.completed_game_team_list import CompletedGameTeamList
from swagger_client.models.event import Event
from swagger_client.models.event_modifier import EventModifier
from swagger_client.models.event_modifier_list import EventModifierList
from swagger_client.models.gear_info import GearInfo
from swagger_client.models.gear_info_list import GearInfoList
from swagger_client.models.gear_stat import GearStat
from swagger_client.models.gear_stat_list import GearStatList
from swagger_client.models.json_localized_name import JsonLocalizedName
from swagger_client.models.match import Match
from swagger_client.models.match_location import MatchLocation
from swagger_client.models.match_location_list import MatchLocationList
from swagger_client.models.match_team import MatchTeam
from swagger_client.models.match_team_list import MatchTeamList
from swagger_client.models.match_team_player import MatchTeamPlayer
from swagger_client.models.match_team_player_list import MatchTeamPlayerList
from swagger_client.models.player import Player
from swagger_client.models.player_club import PlayerClub
from swagger_client.models.player_entry import PlayerEntry
from swagger_client.models.player_entry_completed_game import PlayerEntryCompletedGame
from swagger_client.models.player_entry_completed_game_list import PlayerEntryCompletedGameList
from swagger_client.models.player_icon import PlayerIcon
from swagger_client.models.player_match_status import PlayerMatchStatus
from swagger_client.models.player_match_status_list import PlayerMatchStatusList
from swagger_client.models.player_ranking import PlayerRanking
from swagger_client.models.player_ranking_club import PlayerRankingClub
from swagger_client.models.player_ranking_list import PlayerRankingList
from swagger_client.models.register_match_request import RegisterMatchRequest
from swagger_client.models.register_match_request_players import RegisterMatchRequestPlayers
from swagger_client.models.register_match_response import RegisterMatchResponse
from swagger_client.models.scheduled_event import ScheduledEvent
from swagger_client.models.scheduled_event_location import ScheduledEventLocation
from swagger_client.models.scheduled_events import ScheduledEvents
from swagger_client.models.service_version import ServiceVersion
from swagger_client.models.set_esports_notification_request import SetEsportsNotificationRequest
from swagger_client.models.set_esports_notification_response import SetEsportsNotificationResponse
from swagger_client.models.siege_stats import SiegeStats
from swagger_client.models.star_power import StarPower
from swagger_client.models.star_power_list import StarPowerList
from swagger_client.models.stats import Stats
