# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.scheduled_event import ScheduledEvent  # noqa: E501
from swagger_client.rest import ApiException


class TestScheduledEvent(unittest.TestCase):
    """ScheduledEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduledEvent(self):
        """Test ScheduledEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.scheduled_event.ScheduledEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
