# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.brawlers_api import BrawlersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBrawlersApi(unittest.TestCase):
    """BrawlersApi unit test stubs"""

    def setUp(self):
        self.api = BrawlersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_brawler(self):
        """Test case for get_brawler

        Get information about a brawler.  # noqa: E501
        """
        pass

    def test_get_brawlers(self):
        """Test case for get_brawlers

        Get list of available brawlers.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
