# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.register_match_request_players import RegisterMatchRequestPlayers  # noqa: E501
from swagger_client.rest import ApiException


class TestRegisterMatchRequestPlayers(unittest.TestCase):
    """RegisterMatchRequestPlayers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegisterMatchRequestPlayers(self):
        """Test RegisterMatchRequestPlayers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.register_match_request_players.RegisterMatchRequestPlayers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
