# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.battle_region_list import BattleRegionList  # noqa: E501
from swagger_client.rest import ApiException


class TestBattleRegionList(unittest.TestCase):
    """BattleRegionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBattleRegionList(self):
        """Test BattleRegionList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.battle_region_list.BattleRegionList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
