# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.player_entry_completed_game import PlayerEntryCompletedGame  # noqa: E501
from swagger_client.rest import ApiException


class TestPlayerEntryCompletedGame(unittest.TestCase):
    """PlayerEntryCompletedGame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerEntryCompletedGame(self):
        """Test PlayerEntryCompletedGame"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.player_entry_completed_game.PlayerEntryCompletedGame()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
