# coding: utf-8

# flake8: noqa

"""
    Brawl Stars API

    Brawl Stars API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.2.0"

# import apis into sdk package
from brawlstars.api.brawlers_api import BrawlersApi
from brawlstars.api.clubs_api import ClubsApi
from brawlstars.api.events_api import EventsApi
from brawlstars.api.players_api import PlayersApi
from brawlstars.api.rankings_api import RankingsApi

# import ApiClient
from brawlstars.api_response import ApiResponse
from brawlstars.api_client import ApiClient
from brawlstars.configuration import Configuration
from brawlstars.exceptions import OpenApiException
from brawlstars.exceptions import ApiTypeError
from brawlstars.exceptions import ApiValueError
from brawlstars.exceptions import ApiKeyError
from brawlstars.exceptions import ApiAttributeError
from brawlstars.exceptions import ApiException

# import models into sdk package
from brawlstars.models.accessory import Accessory
from brawlstars.models.banned_brawler_entry import BannedBrawlerEntry
from brawlstars.models.battle import Battle
from brawlstars.models.battle_region import BattleRegion
from brawlstars.models.brawler import Brawler
from brawlstars.models.brawler_info import BrawlerInfo
from brawlstars.models.brawler_stat import BrawlerStat
from brawlstars.models.cancel_match_response import CancelMatchResponse
from brawlstars.models.client_error import ClientError
from brawlstars.models.club import Club
from brawlstars.models.club_member import ClubMember
from brawlstars.models.club_ranking import ClubRanking
from brawlstars.models.completed_game import CompletedGame
from brawlstars.models.completed_game_team import CompletedGameTeam
from brawlstars.models.event import Event
from brawlstars.models.gear_info import GearInfo
from brawlstars.models.gear_stat import GearStat
from brawlstars.models.match import Match
from brawlstars.models.match_location import MatchLocation
from brawlstars.models.match_team import MatchTeam
from brawlstars.models.match_team_player import MatchTeamPlayer
from brawlstars.models.player import Player
from brawlstars.models.player_club import PlayerClub
from brawlstars.models.player_entry import PlayerEntry
from brawlstars.models.player_entry_completed_game import PlayerEntryCompletedGame
from brawlstars.models.player_icon import PlayerIcon
from brawlstars.models.player_match_status import PlayerMatchStatus
from brawlstars.models.player_ranking import PlayerRanking
from brawlstars.models.player_ranking_club import PlayerRankingClub
from brawlstars.models.register_match_request import RegisterMatchRequest
from brawlstars.models.register_match_response import RegisterMatchResponse
from brawlstars.models.scheduled_event import ScheduledEvent
from brawlstars.models.scheduled_event_location import ScheduledEventLocation
from brawlstars.models.service_version import ServiceVersion
from brawlstars.models.set_esports_notification_request import SetEsportsNotificationRequest
from brawlstars.models.set_esports_notification_response import SetEsportsNotificationResponse
from brawlstars.models.siege_stats import SiegeStats
from brawlstars.models.star_power import StarPower
from brawlstars.models.stats import Stats
