# coding: utf-8

"""
    Brawl Stars API

    Brawl Stars API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from brawlstars.models.player_entry_completed_game import PlayerEntryCompletedGame
from brawlstars.models.siege_stats import SiegeStats
from typing import Optional, Set
from typing_extensions import Self

class CompletedGameTeam(BaseModel):
    """
    CompletedGameTeam
    """ # noqa: E501
    score: Optional[StrictInt] = None
    is_winner: Optional[StrictBool] = Field(default=None, alias="isWinner")
    siege: Optional[SiegeStats] = None
    players: Optional[List[PlayerEntryCompletedGame]] = None
    __properties: ClassVar[List[str]] = ["score", "isWinner", "siege", "players"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompletedGameTeam from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of siege
        if self.siege:
            _dict['siege'] = self.siege.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in players (list)
        _items = []
        if self.players:
            for _item_players in self.players:
                if _item_players:
                    _items.append(_item_players.to_dict())
            _dict['players'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompletedGameTeam from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "score": obj.get("score"),
            "isWinner": obj.get("isWinner"),
            "siege": SiegeStats.from_dict(obj["siege"]) if obj.get("siege") is not None else None,
            "players": [PlayerEntryCompletedGame.from_dict(_item) for _item in obj["players"]] if obj.get("players") is not None else None
        })
        return _obj


